#rename to .travis.yml and use in your project
language: ruby
rvm:
- 2.5.1

before_install:
   - nvm install node
   - ruby -v

install:
  - gem install bundle jekyll
  - bundle install
  - npm install -g https://github.com/firebase/firebase-tools.git

before_script:
  - bundle exec jekyll build --verbose
script:
  - firebase deploy --token "$FIREBASE_API_TOKEN"

