#rename to .travis.yml and use in your project
language: ruby
rvm:
- 2.5.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
    - master
    - develop

sudo: required

before_install:
  - nvm install node
  - ruby -v

install:
  - gem install bundler jekyll
  - npm install -g https://github.com/firebase/firebase-tools.git

before_script:
  - bundle exec jekyll build --verbose
script:
  - firebase deploy --token "$FIREBASE_API_TOKEN"